language: c

install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  - sudo apt-get update
  - sudo apt-get install libmono-system-runtime4.0-cil 
  - sudo apt-get install libmono-system-servicemodel4.0a-cil
  - sudo apt-get install libmono-system-web-services4.0-cil
  - sudo apt-get install libmono-system-web2.0-cil
  - sudo apt-get install libmono2.0-cil
  - sudo apt-get install libmono-cil-dev
  - sudo apt-get install mono-devel

script:
  - cp Src/.nuget/mono_support/Microsoft.Build.dll Src/.nuget/Microsoft.Build.dll
  - export EnableNuGetPackageRestore="true"
  - export MONO_IOMAP=all
  - mozroots --import --sync
  - mono --version
  - mono Tools/Rosalia/Rosalia.exe "./Src/Rosalia.Build/Rosalia.Build.csproj"
