language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - sudo apt-get install xsltproc

script:
  - cp Src/.nuget/mono_support/Microsoft.Build.dll Src/.nuget/Microsoft.Build.dll
  - export EnableNuGetPackageRestore="true"
  - export MONO_IOMAP=all
  - mozroots --import --sync
  - mono Tools/Rosalia/Rosalia.exe Src/Rosalia.Build/Rosalia.Build.csproj
